#! /bin/sh
# /etc/init.d/SocketMain.py

### BEGIN INIT INFO
# Provides:          SocketMain
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting App Server"
    # run application you want to start
    nohup python36 /var/AWSappserver/SocketMain.py &> /tmp/nohup.out
    ;;
  stop)
    echo "Stopping App Server"
    # kill application you want to stop
    killall noip2
    ;;
  *)
    nohup python36 /var/AWSappserver/SocketMain.py &> /tmp/nohup.out
    ;;
esac

exit 0
