#! /bin/sh
# /etc/init.d/socketservice 

### BEGIN INIT INFO
# Provides:          socketservice 
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting the App Server"
    # run application you want to start
    python36 /var/AWSappserver/SocketMain.py
    ;;
  stop)
    echo "Stopping the App Server"
    # kill application you want to stop
    killall SocketMain.py
    ;;
  *)
    echo "Starting the App Server"
    python36 /var/AWSappserver/SocketMain.py
    ;;
    ;;
esac

exit 0
